# Generated by Django 6.0 on 2025-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_simplecourse_course_credits_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='simple_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='app1.simplecourse'),
        ),
    ]
