# Generated by Django 6.0 on 2025-12-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_course_name_student_simple_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, help_text='Attendance percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_students', to='app1.simplecourse'),
        ),
    ]
