# Generated by Django 6.0 on 2025-12-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student_attendance_student_selected_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
