# Generated by Django 6.0 on 2025-12-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
