# Generated by Django 6.0 on 2025-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_student_grade_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.AddField(
            model_name='student',
            name='fee_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
