# Generated by Django 6.0 on 2025-12-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_course_fee_student_fee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
